# ComStock™, Copyright (c) 2020 Alliance for Sustainable Energy, LLC. All rights reserved.
# See top level LICENSE.txt file for license terms.

# *******************************************************************************
# OpenStudio(R), Copyright (c) 2008-2018, Alliance for Sustainable Energy, LLC.
# All rights reserved.
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions are met:
#
# (1) Redistributions of source code must retain the above copyright notice,
# this list of conditions and the following disclaimer.
#
# (2) Redistributions in binary form must reproduce the above copyright notice,
# this list of conditions and the following disclaimer in the documentation
# and/or other materials provided with the distribution.
#
# (3) Neither the name of the copyright holder nor the names of any contributors
# may be used to endorse or promote products derived from this software without
# specific prior written permission from the respective party.
#
# (4) Other than as required in clauses (1) and (2), distributions in any form
# of modifications or other derivative works may not use the "OpenStudio"
# trademark, "OS", "os", or any other confusingly similar designation without
# specific prior written permission from Alliance for Sustainable Energy, LLC.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDER(S) AND ANY CONTRIBUTORS
# "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO,
# THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
# ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER(S), ANY CONTRIBUTORS, THE
# UNITED STATES GOVERNMENT, OR THE UNITED STATES DEPARTMENT OF ENERGY, NOR ANY OF
# THEIR EMPLOYEES, BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL,
# EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT
# OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
# INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT,
# STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY
# OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
# *******************************************************************************
# see the URL below for information on how to write OpenStudio measures
# http://nrel.github.io/OpenStudio-user-documentation/reference/measure_writing_guide/

# Dependencies
require 'openstudio'
require 'openstudio/measure/ShowRunnerOutput'
require 'openstudio-standards'
require 'fileutils'

# Start the measure
class HVACHWDiffPressureReset < OpenStudio::Measure::ModelMeasure
  # Load the helper libraries for getting the autosized
  # values for constant and variable speed pump objects.
  require_relative 'resources/HVACSizing.Model'

  # Human readable name
  def name
    return 'Hot Water Pump Differential Pressure Reset'
  end

  # Human readable description
  def description
    return 'This energy efficiency measure (EEM) configures all variable or constant speed pumps identified as secondary hot water loop pumps. Identified pumps are then either replaced (in the case of a constant speed pump) or reconfigured (in the case of a variable speed pump) to operate as a variable speed pump with an aggressive Part Load Performance Curve representing operation of a functional hot water pump differential pressure reset control with a wide range of deviation in zone valve positions. Energy savings will be generated by operating the secondary hot water pump motor for longer periods of time at lower energy consumptive levels.'
  end

  # Human readable description of modeling approach
  def modeler_description
    return "This measure identifies all OS constant or variable speed pump objects attached to the inlet side of the demand loop of a plant loop having both OS:Sizing:Plant Loop type = 'Heating' and OS:PlantLoop Common Pipe Simulation setting = 'CommonPipe',  indicating that a secondary hot water pump is present on the inlet side of the hot water demand loop. If the existing secondary hot water pump is an OS:Pump:ConstantSpeed object, it will be replaced with a new OS:PumpVariableSpeed object configured with the same Rated Flow Rate, Rated Pump Head, Rated Power Consumption, Motor Efficiency and Fraction of Motor Inefficiencies to Fluid Stream as the original pump and a Part Load Performance Curve will be added. If the existing secondary chilled water pump is an OS:PumpVariableSpeed object, a new Part Load Performance Curve will be added. If the Rated Flow Rate of the existing OS:Pump:ConstantSpeed or OS:Pump:VariableSpeed is specified, the Minimum Flow Rate of the modified pump will be set to a value representing 30 percent of the specified Rated Flow Rate. If the Rated Flow Rate of the OS:Pump:ConstantSpeed or OS:Pump:VariableSpeed is Autosized, a sizing run will be executed and the pump design gpm and rated power consumption are retrieved to accurately set the Minimum Flow Rate of the modified pump to a value representing 30 percent of the Autosized design flow rate."
  end

  # Define the arguments that the user will input
  def arguments(model)
    args = OpenStudio::Measure::OSArgumentVector.new

    return args
  end

  # Define what happens when the measure is run
  def run(model, runner, user_arguments)
    super(model, runner, user_arguments)

    # Use the built-in error checking
    if !runner.validateUserArguments(arguments(model), user_arguments)
      return false
    end

    # Initialize variables
    qualified_loops = 0
    qualified_cooling_plant_loop_array = []
    cs_hardsize = 0
    cs_autosize = 0
    vs_hardsize = 0
    vs_autosize = 0

    # Get qualified plant loops
    model.getPlantLoops.each do |plant_loop|
      loop_type = plant_loop.sizingPlant.loopType
      if plant_loop.commonPipeSimulation.is_initialized
        common_pipe_simulation_status = plant_loop.commonPipeSimulation.get
        if loop_type == 'Heating' && common_pipe_simulation_status == 'CommonPipe'
          qualified_cooling_plant_loop_array << plant_loop
        end
      else
        runner.registerWarning("Setting for the attribute 'Common Pipe Simulation' of plant loop named #{plant_loop.name} was blank. The measure will not change this plant loop object.")
      end
    end

    qualified_cooling_plant_loop_array.each do |qualified_loop|
      loop_name = qualified_loop.name.to_s
      qualified_loop.demandComponents.each do |dc|
        if dc.to_PumpConstantSpeed.is_initialized
          qualified_cs_pump = dc.to_PumpConstantSpeed.get

          # Read value for autosizing pump flow
          cs_pump_autosize_status = qualified_cs_pump.isRatedFlowRateAutosized
          if cs_pump_autosize_status == false
            # Retrieve 'hard sized' constant speed pump attributes
            exg_cs_pump_name = qualified_cs_pump.name
            if qualified_cs_pump.ratedFlowRate.is_initialized
              rated_flow_rate = qualified_cs_pump.ratedFlowRate.get
            else
              if rated_flow_rate.nil?
                runner.registerWarning("The rated flow rate attribute of the non-autosized constant speed pump object named #{exg_cs_pump_name} was not defined. Please define this attribute.")
              end
            end
            if qualified_cs_pump.ratedPowerConsumption.is_initialized
              rated_power_consumption = qualified_cs_pump.ratedPowerConsumption.get
            else
              if rated_power_consumption.nil?
                runner.registerWarning("The rated power consumption attribute of the non-autosized constant speed pump object named #{exg_cs_pump_name} was not defined. Please define this attribute.")
              end
            end
            rated_pump_head = qualified_cs_pump.ratedPumpHead
            motor_efficiency = qualified_cs_pump.motorEfficiency
            fraction_to_motor_efficiencies_to_fluid_stream = qualified_cs_pump.fractionofMotorInefficienciestoFluidStream
            pump_control_type = qualified_cs_pump.pumpControlType

            # For centrifugal single stage variable speed pumps, a minimum pump flow rate value of 25% (of the BEP flow rate) is recommended per
            # http://www.districtenergy.org/pdfs/DEMagArticles/3Q06/3q06insideinsights.pdf. To be conservative, this value has been
            # adjusted to 30% in the code to account for pump selections at flows/pressures to the left of the BEP.
            new_vs_pump_min_flow_rate = rated_flow_rate * 0.30

            # Add new variable speed pump to the same inlet node
            new_vs_pump = OpenStudio::Model::PumpVariableSpeed.new(model)

            # Set values for pump performance to match existing
            new_vs_pump.setName("Hard Sized #{exg_cs_pump_name}-> Variable Speed Pump + Static Pressure Reset Control")
            new_vs_pump.setRatedFlowRate(rated_flow_rate)
            new_vs_pump.setRatedPowerConsumption(rated_power_consumption)
            new_vs_pump.setRatedPumpHead(rated_pump_head)
            new_vs_pump.setMotorEfficiency(motor_efficiency)
            new_vs_pump.setFractionofMotorInefficienciestoFluidStream(fraction_to_motor_efficiencies_to_fluid_stream)
            new_vs_pump.setMinimumFlowRate(new_vs_pump_min_flow_rate)
            new_vs_pump.setPumpControlType(pump_control_type)

            # Set values for coefficients for new variable speed pump part load curve
            # Note these values are sourced from Appendix 3.7 of the draft (unpublished) version of
            # ANSI/ASHRAE/IES Standard 90.1-2010 "Performance Rating Method Reference Manual"
            # dated August 2015 for the curve named 'PumpVSDRstPwrRatio_fGPMRatio'
            new_vs_pump.setCoefficient1ofthePartLoadPerformanceCurve(0)
            new_vs_pump.setCoefficient2ofthePartLoadPerformanceCurve(0.0205)
            new_vs_pump.setCoefficient3ofthePartLoadPerformanceCurve(0.4101)
            new_vs_pump.setCoefficient4ofthePartLoadPerformanceCurve(0.5753)

            # Remove previous pump
            dc.remove
            runner.registerInfo("The hard sized constant speed pump object named #{exg_cs_pump_name} has been removed from the hot water plant loop named #{loop_name}.")

            # Add pump to demand inlet node
            hw_demand_inlet_node = qualified_loop.demandInletNode
            new_vs_pump.addToNode(hw_demand_inlet_node)

            # Write info messages
            runner.registerInfo("A variable speed pump with a part load performance curve representing best practice static pressure reset control and named #{new_vs_pump.name} has been added to the hot water plant loop named #{loop_name}. A minimum flow rate  of #{new_vs_pump_min_flow_rate} m3/sec, based on 30% of the rated flow rate, was assigned. All other pump settings - rated flow rate, rated pump head, rated power consumption, motor efficiency, fraction of motor efficiencies to fluid stream and pump control type were re-used from the #{exg_cs_pump_name} constant speed pump object.")
            cs_hardsize += 1
          end

          if cs_pump_autosize_status == true

            # Retrieve attributes from autosized variable speed pump that must have values
            exg_cs_pump_name = qualified_cs_pump.name
            rated_pump_head = qualified_cs_pump.ratedPumpHead
            motor_efficiency = qualified_cs_pump.motorEfficiency
            fraction_to_motor_efficiencies_to_fluid_stream = qualified_cs_pump.fractionofMotorInefficienciestoFluidStream
            pump_control_type = qualified_cs_pump.pumpControlType

            # Perform a sizing run for the autosized constant speed pump
            if model.runSizingRun("#{Dir.pwd}/SizingRun") == false
              runner.registerError('Sizing Run for determining flow of autosized constant speed pump failed to complete - check eplusout.err to debug.')
              return false
            else
              runner.registerInfo("A sizing run for determining the rated flow rate of the autosized secondary hot water constant speed pump named #{exg_cs_pump_name} completed - look in folder #{Dir.pwd}/SizingRun for results.")
            end

            # Retrieve value for autosized constant speed rated flow
            autosized_rated_flow_rate = nil
            if qualified_cs_pump.autosizedRatedFlowRate.is_initialized
              autosized_rated_flow_rate = qualified_cs_pump.autosizedRatedFlowRate.get
            else
              runner.registerError("A sizing run for determining the rated flow rate of the autosized secondary hot water constant speed pump named #{exg_cs_pump_name} did not result in a value for pump rated flow rate.")
            end

            # Retrieve value for autosized pump rated power consumption
            autosized_pump_power_consumption = nil
            if qualified_cs_pump.autosizedRatedFlowRate.is_initialized
              autosized_pump_power_consumption = qualified_cs_pump.autosizedRatedPowerConsumption.get
            else
              runner.registerError("A sizing run for determining the rated power consumption of the autosized secondary hot water constant speed pump named #{exg_cs_pump_name} did not result in a value for pump rated power consumption.")
            end

            # Create new variable speed object for replacing autosized constant speed pump object
            new_vs_pump = OpenStudio::Model::PumpVariableSpeed.new(model)

            # Set values for pump performance to match existing
            new_vs_pump.setName("Autosized #{exg_cs_pump_name}-> Variable Speed Pump + Static Pressure Reset Control")
            new_vs_pump.setRatedFlowRate(autosized_rated_flow_rate)
            new_vs_pump.setRatedPowerConsumption(autosized_pump_power_consumption)
            new_vs_pump.setRatedPumpHead(rated_pump_head)
            new_vs_pump.setMotorEfficiency(motor_efficiency)
            new_vs_pump.setFractionofMotorInefficienciestoFluidStream(fraction_to_motor_efficiencies_to_fluid_stream)

            # For centrifugal single stage pumps, a minimum pump flow rate value of 25% (of the BEP flow rate) is recommended per
            # http://www.districtenergy.org/pdfs/DEMagArticles/3Q06/3q06insideinsights.pdf. To be conservative, this value has been
            # adjusted to 30% in the code to account for pump selections at flows/pressures to the left of the BEP.
            new_vs_pump_min_flow_rate = autosized_rated_flow_rate * 0.30

            new_vs_pump.setMinimumFlowRate(new_vs_pump_min_flow_rate)
            new_vs_pump.setPumpControlType(pump_control_type)

            # Set values for coefficients for new variable speed pump part load curve
            # Note these values are sourced from Appendix 3.7 of the draft (unpublished) version of
            # ANSI/ASHRAE/IES Standard 90.1-2010 "Performance Rating Method Reference Manual"
            # dated August 2015 for the curve named 'PumpVSDRstPwrRatio_fGPMRatio'
            new_vs_pump.setCoefficient1ofthePartLoadPerformanceCurve(0)
            new_vs_pump.setCoefficient2ofthePartLoadPerformanceCurve(0.0205)
            new_vs_pump.setCoefficient3ofthePartLoadPerformanceCurve(0.4101)
            new_vs_pump.setCoefficient4ofthePartLoadPerformanceCurve(0.5753)

            # Remove previous pump
            dc.remove
            runner.registerInfo("The autosized secondary hot water constant speed pump object named #{exg_cs_pump_name} has been removed from the hot water plant loop named #{loop_name}.")

            # Add pump to demand inlet node
            hw_demand_inlet_node = qualified_loop.demandInletNode
            new_vs_pump.addToNode(hw_demand_inlet_node)

            # Write info messages
            runner.registerInfo("A secondary hot water variable speed pump with a part load performance curve representing best practice static pressure reset control and named #{new_vs_pump.name} has been added to the hot water plant loop named plant loop named #{loop_name}. A minimum flow rate of #{new_vs_pump_min_flow_rate} m3/sec, based on 30% of the rated flow rate, was assigned. This object replaces the autosized constant speed pump named #{exg_cs_pump_name} located on the hot water plant loop named #{loop_name}. A sizing run was executed for determining variable speed pump settings for rated flow rate and rated power consumption. Values for pump head, motor efficiency, fraction of motor efficiencies to fluid stream and control type from the autosized constant speed pump object named #{exg_cs_pump_name} object were re-used.")
            cs_autosize += 1

          end
        end

        if dc.to_PumpVariableSpeed.is_initialized
          qualified_vs_pump = dc.to_PumpVariableSpeed.get

          # Read value for autosizing variable speed pump based on rated pump flow setting
          vs_pump_autosize_status = qualified_vs_pump.isRatedFlowRateAutosized
          if vs_pump_autosize_status == false
            # Retrieve 'hard sized' variable speed pump attributes
            exg_vs_pump_name = qualified_vs_pump.name
            if qualified_vs_pump.ratedFlowRate.is_initialized
              rated_flow_rate = qualified_vs_pump.ratedFlowRate.get
            else
              if rated_flow_rate.nil?
                runner.registerWarning("The rated flow rate attribute of the non-autosized secondary hot water variable speed pump object named #{exg_vs_pump_name} was not defined. Please define this attribute.")
              end
            end
            if qualified_vs_pump.ratedPowerConsumption.is_initialized
              rated_power_consumption = qualified_vs_pump.ratedPowerConsumption.get
            else
              if rated_power_consumption.nil?
                runner.registerWarning("The rated power consumption attribute of the non-autosized secondary hot water variable speed pump object named #{exg_vs_pump_name} was not defined. Please define this attribute.")
              end
            end
            rated_pump_head = qualified_vs_pump.ratedPumpHead
            motor_efficiency = qualified_vs_pump.motorEfficiency
            fraction_to_motor_efficiencies_to_fluid_stream = qualified_vs_pump.fractionofMotorInefficienciestoFluidStream
            exg_hard_sized_vs_coef_1 = qualified_vs_pump.getCoefficient1ofthePartLoadPerformanceCurve
            exg_hard_sized_vs_coef_2 = qualified_vs_pump.getCoefficient2ofthePartLoadPerformanceCurve
            exg_hard_sized_vs_coef_3 = qualified_vs_pump.getCoefficient3ofthePartLoadPerformanceCurve
            exg_hard_sized_vs_coef_4 = qualified_vs_pump.getCoefficient4ofthePartLoadPerformanceCurve
            exg_hard_sized_vs_min_flow_rate = qualified_vs_pump.getMinimumFlowRate
            pump_control_type = qualified_vs_pump.pumpControlType

            # For centrifugal single stage pumps, a minimum pump flow rate value of 25% (of the BEP flow rate) is recommended per
            # http://www.districtenergy.org/pdfs/DEMagArticles/3Q06/3q06insideinsights.pdf. To be conservative, this value has been
            # adjusted to 30% in the code to account for pump selections at flows/pressures to the left of the BEP.
            new_vs_pump_min_flow_rate = rated_flow_rate * 0.30

            # Add new variable speed pump to the same inlet node
            new_vs_pump = OpenStudio::Model::PumpVariableSpeed.new(model)

            # Set values for pump performance to match existing
            new_vs_pump.setName("Hard Sized #{exg_vs_pump_name}-> Variable Speed Pump + Static Pressure Reset Control")
            new_vs_pump.setRatedFlowRate(rated_flow_rate)
            new_vs_pump.setRatedPowerConsumption(rated_power_consumption)
            new_vs_pump.setRatedPumpHead(rated_pump_head)
            new_vs_pump.setMotorEfficiency(motor_efficiency)
            new_vs_pump.setFractionofMotorInefficienciestoFluidStream(fraction_to_motor_efficiencies_to_fluid_stream)
            new_vs_pump.setMinimumFlowRate(new_vs_pump_min_flow_rate)
            new_vs_pump.setPumpControlType(pump_control_type)

            # Set values for coefficients for new variable speed pump part load curve
            # Note these values are sourced from Appendix 3.7 of the draft (unpublished) version of
            # ANSI/ASHRAE/IES Standard 90.1-2010 "Performance Rating Method Reference Manual"
            # dated August 2015 for the curve named 'PumpVSDRstPwrRatio_fGPMRatio'
            new_vs_pump.setCoefficient1ofthePartLoadPerformanceCurve(0)
            new_vs_pump.setCoefficient2ofthePartLoadPerformanceCurve(0.0205)
            new_vs_pump.setCoefficient3ofthePartLoadPerformanceCurve(0.4101)
            new_vs_pump.setCoefficient4ofthePartLoadPerformanceCurve(0.5753)

            # Remove previous pump
            dc.remove
            runner.registerInfo("The hard sized secondary hot water variable speed pump object named #{exg_vs_pump_name} has been removed from the hot water plant loop named #{loop_name}.")

            # Add pump to demand inlet node
            hw_demand_inlet_node = qualified_loop.demandInletNode
            new_vs_pump.addToNode(hw_demand_inlet_node)

            # Write info messages
            runner.registerInfo("A secondary hot water variable speed pump with a part load performance curve representing best practice static pressure reset control and named #{new_vs_pump.name} has been added to the hot water plant loop named #{loop_name}. A minimum flow rate  of #{new_vs_pump_min_flow_rate} m3/sec, based on 30% of the rated flow rate, was assigned. All other pump settings - rated flow rate, rated pump head, rated power consumption, motor efficiency, fraction of motor efficiencies to fluid stream and pump control type were re-used from the #{exg_vs_pump_name} variable speed pump object .")
            vs_hardsize += 1

          end

          if vs_pump_autosize_status == true

            # Retrieve attributes from autosized variable speed pump that must have values
            exg_vs_pump_name = qualified_vs_pump.name
            rated_pump_head = qualified_vs_pump.ratedPumpHead
            motor_efficiency = qualified_vs_pump.motorEfficiency
            fraction_to_motor_efficiencies_to_fluid_stream = qualified_vs_pump.fractionofMotorInefficienciestoFluidStream
            exg_hard_sized_vs_coef_1 = qualified_vs_pump.getCoefficient1ofthePartLoadPerformanceCurve
            exg_hard_sized_vs_coef_2 = qualified_vs_pump.getCoefficient2ofthePartLoadPerformanceCurve
            exg_hard_sized_vs_coef_3 = qualified_vs_pump.getCoefficient3ofthePartLoadPerformanceCurve
            exg_hard_sized_vs_coef_4 = qualified_vs_pump.getCoefficient4ofthePartLoadPerformanceCurve
            exg_hard_sized_vs_min_flow_rate = qualified_vs_pump.getMinimumFlowRate
            pump_control_type = qualified_vs_pump.pumpControlType

            # Perform a sizing run for the autosized variable speed pump
            if model.runSizingRun("#{Dir.pwd}/SizingRun") == false
              runner.registerError("Sizing Run for determining flow of autosized secondary hot water variable speed pump named named #{exg_vs_pump_name} failed to complete - check eplusout.err to debug. Look in folder #{Dir.pwd}")
              return false
            else
              runner.registerInfo("A sizing run for determining the rated flow rate of the autosized secondary hot water constant speed pump named #{exg_vs_pump_name} completed - look in folder #{Dir.pwd}/SizingRun for results.")
            end

            # Retrieve value for autosized variable speed rated flow
            autosized_rated_flow_rate = nil
            if qualified_vs_pump.autosizedRatedFlowRate.is_initialized
              autosized_rated_flow_rate = qualified_vs_pump.autosizedRatedFlowRate.get
            else
              runner.registerError("A sizing run for determining the rated flow rate of the autosized secondary hot water variable speed pump named #{exg_vs_pump_name} did not result in a value for pump rated flow rate.")
            end

            # Retrieve value for autosized pump rated power consumption
            autosized_pump_power_consumption = nil
            if qualified_vs_pump.autosizedRatedFlowRate.is_initialized
              autosized_pump_power_consumption = qualified_vs_pump.autosizedRatedPowerConsumption.get
            else
              runner.registerError("A sizing run for determining the rated power consumption of the autosized secondary hot water variable speed pump named #{exg_vs_pump_name} did not result in a value for pump rated power consumption.")
            end

            # Create new variable speed object for replacing autosized constant speed pump object
            new_vs_pump = OpenStudio::Model::PumpVariableSpeed.new(model)

            # Set values for pump performance to match existing
            new_vs_pump.setName("Autosized #{exg_vs_pump_name}-> Variable Speed Pump + Static Pressure Reset Control")
            new_vs_pump.setRatedFlowRate(autosized_rated_flow_rate)
            new_vs_pump.setRatedPowerConsumption(autosized_pump_power_consumption)
            new_vs_pump.setRatedPumpHead(rated_pump_head)
            new_vs_pump.setMotorEfficiency(motor_efficiency)
            new_vs_pump.setFractionofMotorInefficienciestoFluidStream(fraction_to_motor_efficiencies_to_fluid_stream)

            # For centrifugal single stage pumps, a minimum pump flow rate value of 25% (of the BEP flow rate) is recommended per
            # http://www.districtenergy.org/pdfs/DEMagArticles/3Q06/3q06insideinsights.pdf. To be conservative, this value has been
            # adjusted to 30% in the code to account for pump selections at flows/pressures to the left of the BEP.
            new_vs_pump_min_flow_rate = autosized_rated_flow_rate * 0.30

            new_vs_pump.setMinimumFlowRate(new_vs_pump_min_flow_rate)
            new_vs_pump.setPumpControlType(pump_control_type)

            # Set values for coefficients for new variable speed pump part load curve
            # Note these values are sourced from Appendix 3.7 of the draft (unpublished) version of
            # ANSI/ASHRAE/IES Standard 90.1-2010 "Performance Rating Method Reference Manual"
            # dated August 2015 for the curve named 'PumpVSDRstPwrRatio_fGPMRatio'
            new_vs_pump.setCoefficient1ofthePartLoadPerformanceCurve(0)
            new_vs_pump.setCoefficient2ofthePartLoadPerformanceCurve(0.0205)
            new_vs_pump.setCoefficient3ofthePartLoadPerformanceCurve(0.4101)
            new_vs_pump.setCoefficient4ofthePartLoadPerformanceCurve(0.5753)

            # Remove previous pump
            dc.remove
            runner.registerInfo("The autosized secondary hot water variable speed pump object named #{exg_vs_pump_name} has been removed from the hot water plant loop named #{loop_name}.")

            # Add pump to demand inlet node
            hw_demand_inlet_node = qualified_loop.demandInletNode
            new_vs_pump.addToNode(hw_demand_inlet_node)

            # Write info messages
            runner.registerInfo("A secondary hot water variable speed pump with a part load performance curve representing best practice static pressure reset control and named #{new_vs_pump.name} has been added to the hot water plant loop named #{loop_name}. A minimum flow rate of #{new_vs_pump_min_flow_rate} m3/sec, based on 30% of the rated flow rate, was assigned. This object replaces the autosized constant speed pump named #{exg_vs_pump_name} located on the hot water plant loop named #{loop_name}. A sizing run was executed for determining secondary hot water variable speed pump settings for rated flow rate and rated power consumption. Values for pump head, motor efficiency, fraction of motor efficiencies to fluid stream and control type from the autosized variable speed pump object named #{exg_vs_pump_name} object were re-used.")
            vs_autosize += 1

          end
        end
      end

      if qualified_cooling_plant_loop_array.empty?
        runner.registerAsNotApplicable("The model does not contain any hot water loops with a plant_loop.commonPipeSimulation setting = 'Common Pipe'. The measure is not applicible.")
        return false
      end
    end

    total = cs_hardsize + cs_autosize + vs_hardsize + vs_autosize

    # Check for not applicible conditions
    if total == 0
      runner.registerAsNotApplicable('The model does not contain any constant or variable speed secondary hot water pump objects for this measure to apply a differential pressure reset control strategy to. The measure is not applicible.')
      return false
    end

    # Generate initial conditions message
    runner.registerInitialCondition("The measure began with #{total} qualified constant or variable speed secondary hot water pump objects that this measure will modify.")

    # Generate final conditions message
    runner.registerFinalCondition("This measure added differential pressure pumping reset strategies to #{cs_hardsize} hardsized constant speed pump object(s), #{cs_autosize} autosized constant speed pump object(s), #{vs_hardsize} hardsized variable speed pump object(s) and , #{vs_autosize} autosized variable speed pump object(s) serving #{qualified_cooling_plant_loop_array.size} secondary hot water loop(s) which were altered by this measure.")
    runner.registerValue('hvac_hw_pump_reset_num_hw_pumps', total)
    return true
  end
end

# Register the measure to be used by the application
HVACHWDiffPressureReset.new.registerWithApplication
