source 'http://rubygems.org'
ruby '~> 3.2.0'

# Bug in addressable to 2.8.1 and patched version has an issue https://github.com/NREL/OpenStudio/issues/4870
gem 'addressable', '= 2.8.1'

# This removes the rubocop runtime dependency on 'json ~> 2.3'.
gem 'rubocop', github: 'jmarrec/rubocop', ref: '1.50.0-no_json'
gem 'rubocop-rake'
gem 'rubocop-rspec'

gem 'bcl', '= 0.9.1'
gem 'openstudio-extension', '= 0.9.1'
gem 'openstudio-workflow', '= 2.5.0'
# gem 'openstudio-standards', '= 0.8.2'
gem 'openstudio-standards', git: 'https://github.com/NREL/openstudio-standards.git', ref: '359f4c075fcdf43be9007b419f16e6b7fd2b3c6d'
# gem 'openstudio-standards', path: "C:/GitRepos/openstudio-standards" # Use this format when testing openstudio-standards changes locally
gem 'openstudio-geb', git: 'https://github.com/LBNL-ETA/Openstudio-GEB-gem.git', ref: '87da5c2678327b73eef54d2364f46225154bb956'
gem 'tbd', '= 3.4.4'

group :test do
  gem 'minitest-junit', '= 1.1.0'
  gem 'minitest-reporters', '= 1.4.3'
end
